version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@12@
      POSTGRES_DB: oriondb
    ports:
      - '54320:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
