CREATE TABLE IF NOT EXISTS needs_posts (
  id SERIAL PRIMARY KEY,
  form_type VARCHAR(50) NOT NULL,
  form_data JSONB NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
